name = "watchanimeworld-api"
main = "src/index.ts"
compatibility_date = "2024-12-05"
account_id = "cd4ab75cca150f63177325a6bb1c355f"

[build]
command = "bun run build"

[env.production]
name = "watchanimeworld-api"
